export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'

export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY'

export const SET_PLAY_LIST = 'SET_PLAY_LIST'

export const SET_CURRENT_PLAY_INDEX = 'SET_CURRENT_PLAY_INDEX'

export const SET_PLAYING = 'SET_PLAYING'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_PLAY_LIST_VISIBLE = 'SET_PLAY_LIST_VISIBLE'